### ISSUE TITLE
2D keypoints used for fitting

### ISSUE THREAD

**Issue by mkocabas** [deepmind/Temporal-3D-Pose-Kinetics#4]
Hi @hmph and @cdoersch,

Thanks for releasing the dataset. Is it also possible to release the 2D keypoints used for fitting, too? Thanks!

**Comment by cdoersch** [comment]
Greetings @mkocabas , the 2d keypoints are already available in the dataset: see the '2d_keypoints' field.

**Comment by mkocabas** [comment]
Thanks for your reply. `2d_keypoints` field contains the projected keypoints using SMPL. However, I intend to use the detected 2D keypoints obtained through Papandreou et al.'s method [1].

[1] G. Papandreou, T. Zhu, N. Kanazawa, A. Toshev, J. Tompson,  C. Bregler,  and K. Murphy.   Towards accurate multi-person pose estimation in the wild.  In CVPR, 2017

**Comment by cdoersch** [comment]
Sorry, we don't currently provide those, nor do we have any plans to.

**Comment by mkocabas** [comment]
Thanks for the reply!
